---
- set_fact:
    group_inventory_groups: 
      - cluster
      - "{{ [cluster_name, group.name] | join('_')}}"
      - "{{ group.name }}"
    group_extra_groups: "{{ cluster_groups | selectattr('name', 'equalto', group.name) | map(attribute='extra_groups') | first | default([]) }}"

- name: Determine ProxyJump ssh parameters
  set_fact:
    group_jump_params: "-o StrictHostKeyChecking=no -o ProxyJump={{ cluster_gw_user }}@{{ cluster_gw_ip }}"
  when:
    - cluster_gw_group is defined
    - cluster_gw_group != group.name

- name: "Add nodes for group: {{ group.name }}"
  add_host:
    name: "{{ node.name }}"
    groups: "{{ group_inventory_groups + group_extra_groups }}"
    ansible_host: "{{ node.ip }}"
    ansible_user: "{{ cluster_deploy_user | default('root') }}"
    ansible_ssh_private_key_file: "{{ cluster_private_key_file }}"
    ansible_ssh_common_args: "{{ group_jump_params | default(omit) }}"
  with_items: "{{ group.nodes }}"
  loop_control:
    loop_var: node
