---

- name: Get inventory groups for node group
  set_fact:
    node_group_default_groups:
      - cluster
      - "cluster_{{ cluster_name }}"
      - "{{ node_group.name }}"
      - "{{ cluster_name }}_{{ node_group.name }}"

- name: Add nodes for node group
  add_host:
    name: "{{ node.name }}"
    groups: "{{ node_group_default_groups + (node.inventory_groups | default([], true)) }}"
    ansible_host: "{{ node.ip }}"
    ansible_user: "{{ cluster_ssh_user }}"
    ansible_ssh_private_key_file: "{{ cluster_ssh_private_key_file }}"
    # If there is a gateway proxy command set, use it
    #   Note that the gateway group is processed before the proxy command is set
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null {{ cluster_gw_ssh_proxy_command | default('') }}"
  loop: "{{ node_group.nodes }}"
  loop_control:
    loop_var: node
    label: "{{ node.name }}"

# I tried 'set_fact: "{{ node.facts }}"', but it didn't work
# So because blocks can't loop, we have to have another file
- name: Set stored facts for nodes in node group
  include_tasks: set_node_facts.yml
  loop: "{{ node_group.nodes }}"
  loop_control:
    loop_var: node
    label: "{{ node.name }}"
