---
- set_fact:
    group_inventory_groups:
      - cluster
      - "{{ [cluster_name, group.name] | join('_')}}"
      - "{{ group.name }}"
    group_extra_groups: "{{ cluster_groups | selectattr('name', 'equalto', group.name) | map(attribute='extra_groups') | first | default([]) }}"

- set_fact:
    gw_host_key: "{{ hostvars[groups[cluster_gw_group] | first]['ansible_ssh_private_key_file'] }}"
  when:
    - cluster_gw_group is defined
    - cluster_gw_group != group.name

- name: Determine SSH proxy command
  set_fact:
    group_proxy_command: "-o ProxyCommand='ssh -i {{ gw_host_key }} -o UserKnownHostsFile={{ cluster_known_hosts_file }} -W %h:%p {{ cluster_gw_user }}@{{ cluster_gw_ip }}'"
  when:
    - cluster_gw_group is defined
    - cluster_gw_group != group.name

- name: "Add nodes for group: {{ group.name }}"
  add_host:
    name: "{{ node.name }}"
    groups: "{{ group_inventory_groups + group_extra_groups }}"
    ansible_host: "{{ node.ip }}"
    ansible_user: "{{ cluster_deploy_user | default('root') }}"
    ansible_ssh_private_key_file: "{{ cluster_private_key_file }}"
    # Include the SSH known hosts file
    ansible_ssh_common_args: "-o UserKnownHostsFile={{ cluster_known_hosts_file }} {{ group_proxy_command | default('') }}"
  with_items: "{{ group.nodes }}"
  loop_control:
    loop_var: node
