---

- name: Get inventory groups for node group
  set_fact:
    node_group_default_groups:
      - cluster
      - "cluster_{{ cluster_name }}"
      - "{{ node_group.name }}"
      - "{{ cluster_name }}_{{ node_group.name }}"
    node_group_inventory_groups: "{{ node_group.inventory_groups | default([], true) }}"

- name: Add nodes for node group
  add_host:
    name: "{{ node.name }}"
    groups: "{{ node_group_default_groups + node_group_inventory_groups }}"
    ansible_host: "{{ node.ip }}"
    ansible_user: "{{ cluster_ssh_user }}"
    ansible_ssh_private_key_file: "{{ cluster_ssh_private_key_file }}"
    # Include the SSH known hosts file
    # If there is a gateway proxy command set, use that also
    #   Note that the gateway group is processed before the proxy command is set
    ansible_ssh_common_args: "-o ForwardAgent=yes -o UserKnownHostsFile={{ cluster_ssh_known_hosts_file }} {{ cluster_gw_ssh_proxy_command | default('') }}"
  loop: "{{ node_group.nodes }}"
  loop_control:
    loop_var: node
    label: "{{ node.name }}"

- name: Set stored facts for nodes in node group
  set_fact:
    "{{ item.1.key }}": "{{ item.1.value }}"
  delegate_to: "{{ item.0.name }}"
  delegate_facts: true
  loop: "{{ node_group.nodes | product(node_group.facts | default({}, true) | dict2items) | list }}"
  loop_control:
    label: "{{ item.0.name }}, {{ item.1.key }}"
