---

- name: Create or update cluster Heat stack
  os_stack:
    name: "{{ cluster_name }}"
    auth_type: "{{ cluster_auth_type or omit }}"
    auth: "{{ cluster_auth or omit }}"
    state: "{{ cluster_state }}"
    environment: "{{ cluster_environment }}"
    template: "{{ cluster_template }}"
    parameters: "{{ cluster_parameters }}"
    tag: "{{ cluster_tag | default(omit)}}"
  register: cluster_stack

- block:
    - name: Extract facts from stack
      set_fact:
        cluster_node_groups: "{{ (cluster_stack.stack.outputs | selectattr('output_key', 'equalto', 'node_groups') | first).output_value }}"
        cluster_private_key: "{{ (cluster_stack.stack.outputs | selectattr('output_key', 'equalto', 'deploy_private_key') | first).output_value }}"

    - name: Extract facts for cluster gateway host from cluster stack
      set_fact:
        cluster_gw_user: "{{ cluster_parameters.cluster_groups | selectattr('name', 'equalto', cluster_gw_group) | map(attribute='user') | first }}"
        cluster_gw_ip: "{{ (cluster_node_groups | selectattr('name', 'equalto', cluster_gw_group) | first).nodes | map(attribute='ip') | first }}"
        cluster_node_group_gw: "{{ cluster_node_groups | selectattr('name', 'equalto', cluster_gw_group) | list }}"
      when:
        - cluster_gw_group is defined
        - cluster_gw_user is not defined or cluster_gw_ip is not defined

    - name: Set private key file fact
      set_fact:
        cluster_private_key_file: "{{ private_data_dir }}/{{ cluster_name }}_ssh_private_key"

    - name: Write cluster private key
      copy:
        content: "{{ cluster_private_key }}"
        dest: "{{ cluster_private_key_file }}"
        mode: 0600

    - name: Build in-memory inventory for gateway group/host
      include_tasks: add_inventory_group.yml
      with_items: "{{ cluster_node_group_gw }}"
      loop_control:
        loop_var: group
      when:
        - cluster_gw_group is defined
        - cluster_gw_host is not defined

    - name: Build in-memory inventory
      include_tasks: add_inventory_group.yml
      with_items: "{{ cluster_node_groups }}"
      loop_control:
        loop_var: group

    - name: Select gateway host where group is designated
      set_fact:
        cluster_gw_host: "{{ groups[cluster_gw_group] | first }}"
      when:
        - cluster_gw_group is defined
        - cluster_gw_host is not defined

    # We do this by attempting to ping the nodes
    - name: Wait for nodes to become accessible
      block:
        # First, wait for hosts in the gateway group
        - name: Wait for gateway hosts
          include_tasks: wait_for_hosts.yml
          vars:
            cluster_scan_host: "{{ inventory_hostname }}"
            hosts: "{{ groups[cluster_gw_group] }}"
          when: cluster_gw_group is defined

        # Then wait for the rest of the cluster hosts
        - name: Wait for cluster hosts
          include_tasks: wait_for_hosts.yml
          vars:
            cluster_scan_host: "{{ cluster_gw_host | default(inventory_hostname) }}"
            hosts: "{{ query('inventory_hostnames', 'cluster:!' + cluster_gw_group) }}"
  when: cluster_state == 'present' and not cluster_stack_update_only
