---

- name: Determine if gateway configuration is required
  set_fact:
    # If a proxy command has already been specified, there is nothing to do
    cluster_configure_gateway: "{{ cluster_gw_group is defined and cluster_gw_ssh_proxy_command is not defined }}"

- name: Configure cluster gateway
  block:
    - name: Find gateway node group
      set_fact:
        cluster_gw_node_group: "{{ cluster_node_groups | selectattr('name', 'equalto', cluster_gw_group) | first }}"

    - name: Build in-memory inventory for gateway group
      include_tasks: add_inventory_group.yml
      vars:
        cluster_gateway_host: true
        node_group: "{{ cluster_gw_node_group }}"

    - name: Wait for gateway host(s) to become available
      wait_for_connection:
        # Wait for 5 mins for host to become available
        timeout: 300
      delegate_to: "{{ host }}"
      loop: "{{ cluster_gw_node_group.nodes | map(attribute='name') | list }}"
      loop_control:
        loop_var: host

    - name: Set cluster gateway facts
      set_fact:
        cluster_gw_ssh_user: "{{ cluster_ssh_user }}"
        cluster_gw_ssh_private_key_file: "{{ cluster_ssh_private_key_file }}"
        cluster_gw_ip: "{{ cluster_gw_node_group.nodes | map(attribute='ip') | first }}"
        cluster_gw_inventory_hostname: "{{ cluster_gw_node_group.nodes | map(attribute='name') | first }}"

    - name: Set cluster gateway proxy command
      set_fact:
        cluster_gw_ssh_proxy_command: "-o ProxyCommand='ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -W %h:%p {{ cluster_gw_ssh_user }}@{{ cluster_gw_ip }}'"
  when: cluster_configure_gateway | bool

- name: Set non-gateway node groups (gateway present)
  set_fact:
    cluster_non_gateway_node_groups: "{{ cluster_node_groups | rejectattr('name', 'equalto', cluster_gw_group) | list }}"
  when: cluster_configure_gateway | bool

- name: Set non-gateway node groups (no gateway present)
  set_fact:
    cluster_non_gateway_node_groups: "{{ cluster_node_groups }}"
  when: not (cluster_configure_gateway | bool)

- name: Build in-memory inventory
  include_tasks: add_inventory_group.yml
  loop: "{{ cluster_non_gateway_node_groups }}"
  loop_control:
    loop_var: node_group
    label: "{{ node_group.name }}"

- name: Wait for nodes to become accessible
  wait_for_connection:
    # Wait for 5 mins for host to become available
    timeout: 300
  delegate_to: "{{ host }}"
  loop: "{{ cluster_non_gateway_node_groups | map(attribute='nodes') | flatten | map(attribute='name') | list }}"
  loop_control:
    loop_var: host
