---

- name: Wait for access to SSH port on nodes
  wait_for:
    host: "{{ hostvars[host].ansible_host }}"
    port: 22
    state: started
    timeout: 600
  delegate_to: "{{ cluster_ssh_keyscan_host }}"

- name: "Wait for hosts to become available"
  ping:
  delegate_to: "{{ host }}"
  register: host_available
  failed_when: host_available is failed
  until: host_available is succeeded
  retries: 60
  delay: 5
