---
- set_fact:
    cluster_scan_host: "{{ inventory_hostname }}"

- set_fact:
    cluster_scan_host: "{{ cluster_gw_host }}"
  when:
    - cluster_gw_host is defined
    - cluster_gw_group is defined
    - host not in groups[cluster_gw_group]

- name: Wait for access to SSH port on nodes
  wait_for:
    host: "{{ hostvars[host].ansible_host }}"
    port: 22
    state: started
    timeout: 600
  delegate_to: "{{ cluster_scan_host }}"

- name: Scan for SSH keys
  command: ssh-keyscan {{ hostvars[host].ansible_host }}
  register: keyscan_result
  changed_when: False
  delegate_to: "{{ cluster_scan_host }}"

- name: Ensure servers are in SSH known hosts
  blockinfile:
    block: |
      {% for key in keyscan_result.stdout_lines %}
      {{ key }}
      {% endfor %}
    create: true
    marker: "# {mark} P3-APPLIANCES MANAGED BLOCK FOR {{ cluster_name }}.{{ host }}"
    path: "~/.ssh/known_hosts"

- name: "Wait for {{ host }} to become available"
  ping:
  delegate_to: "{{ host }}"
  register: host_available
  until: host_available is succeeded
  retries: 60
  delay: 5
