---
resource_registry:
  "Cluster::Node": "./resources/node.yaml"
  "Cluster::NodeWithRootVolume": "./resources/node-with-root-volume.yaml"
  "Cluster::Node::AttachedVolumes": "./resources/node-attached-volumes.yaml"
  "Cluster::Group": "./resources/group.yaml"

  # Node network configuration: JASMIN use cases envisage a single
  # network port on a common tenant network.  The port will either
  # have a floating IP or not, and the floating IP will be
  # pre-allocated to the project.

  "Cluster::NodeNet": "./resources/nodenet-1.yaml"     # A backwards-compatible default
  "Cluster::NodeNet1": "./resources/nodenet-1.yaml"
  "Cluster::NodeNet1WithPreallocatedFIP": "./resources/nodenet-w-prealloc-fip.yaml"
