---
heat_template_version: train


description: >
  Resource for a port on a named network without a floating IP.


parameters:
  cluster_network:
    type: string
    label: Network to which the nodes should be attached
    constraints:
      - custom_constraint: neutron.network

  cluster_group:
    type: json
    label: Dictionary of properties for the node group

  node_idx:
    type: number
    label: Node index within group


resources:
  port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: cluster_network }


outputs:
  OS::stack_id:
    value: { get_resource: port }

  primary_ip:
    value: { get_attr: [port, fixed_ips, 0, ip_address] }
