---
heat_template_version: queens


description: >
  Resource for a port on a named network with a pre-existing floating IP associated.


parameters:
  cluster_network:
    type: string
    label: Network to which the nodes should be attached
    constraints:
      - custom_constraint: neutron.network

  cluster_group:
    type: json
    label: Dictionary of properties for the node group

  node_idx:
    type: number
    label: Node index within group


resources:
  port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: cluster_network }

  floating_ip_association:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_param: [cluster_group, nodenet_fips, { get_param: node_idx }, uuid] }
      port_id: { get_resource: port }
      fixed_ip_address: { get_attr: [port, fixed_ips, 0, ip_address] }


outputs:
  OS::stack_id:
    value: { get_resource: port }

  primary_ip:
    value: { get_param: [cluster_group, nodenet_fips, { get_param: node_idx }, ip] }
